train_file: ['/mnt/sda/lpf/data/vqa/data_PathVQA/pathvqa_train.json',
             '/mnt/sda/lpf/data/vqa/data_PathVQA/pathvqa_val.json']

test_file: ['/mnt/sda/lpf/data/vqa/data_PathVQA/pathvqa_test.json']

answer_list: '/mnt/sda/lpf/data/vqa/data_PathVQA/answer_trainval_list.json'


vqa_root: '/mnt/sda/lpf/data/vqa/data_PathVQA/images/'  # PathVQA

image_res: 384
batch_size_train: 8  # 32
batch_size_test: 4
k_test: 128

alpha: 0.4
distill: False
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 40, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
