train_file: [
    '/mnt/sda/lpf/data/medical/medical_image_caption/clef2022/clef2022_train.json',
    '/mnt/sda/lpf/data/medical/medical_image_caption/clef2022/clef2022_val.json',
]
image_root: '/mnt/sda/lpf/data/medical/medical_image_caption/'
bert_config: 'configs/config_bert.json'
vit_mae_pretrain_path: '/mnt/sda/lpf/weights/pre_training/mae_pretrain_vit_base.pth'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 16
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 30, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 20, cooldown_epochs: 0}
